name: 'CodeQL Composite Action'
description: 'Composite action handling all elements of CodeQL scanning'
inputs:
  language:
    description: 'Language or set of languages to scan for using CodeQL'
    required: true
  GITHUB_TOKEN:
    description: 'Derivative token for using the GitHub REST API'
    required: false
  GITHUB_REPOSITORY:
    description: 'Calling repository of composite actions'
    reauired: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: ${{ github.repository }}
        fetch-depth: 0

    #- name: Test Composite Actions
      #shell: bash
      #run: |
        #echo "Testing Composite action"
        #pwd
        #ls -a
        #echo ${{ inputs.language }}

    # Initializes the CodeQL tools for scanning [test].
    #- name: Initialize CodeQL
      #uses: github/codeql-action/init@v2
      #with:
        #languages: ${{ inputs.language }}
        #config-file: ./.github/codeql/codeql-config.yml

    #- name: Autobuild
      #uses: github/codeql-action/autobuild@v2

    #- name: Perform CodeQL Analysis
      #uses: github/codeql-action/analyze@v2
      #with:
        #category: "/language:${{ inputs.language }}"

    - name: Create GitHub Issues
      shell: bash
      run: |
        ls -a
        python parse-sarif.py